### ISSUE TITLE
Mobile clients: Android & iOS release date?

### ISSUE THREAD

**Issue by zerodwide** [ssrlive/overtls#6]
Thanks for your great work!

When we could use it on mobiles?

**Comment by ssrlive** [comment]
yes, you can integrate this project to your iOS / Android App as your wish.

**Comment by ssrlive** [comment]
Actually, it's easy to do this job based on https://github.com/ShadowsocksR-Live/iShadowsocksR and https://github.com/ShadowsocksR-Live/ssrDroid .

**Comment by zerodwide** [comment]
Thank @ssrlive for reply
I am familiar with SSROT and using it on Android & Linux. 
So overtls is just the same SSROT on rust language?

**Comment by ssrlive** [comment]
No. Overtls is equivalent to an extremely simple implementation written in Rust language after removing SSR and SS from SSROT, and it only retains OT.

**Comment by zerodwide** [comment]
Nice!
its so great that client has to need to be changed!

**Comment by ssrlive** [comment]
[ssrDroid](https://github.com/shadowsocksr-live/ssrdroid/releases/latest/) now support overtls directly.
